Description: >
  This service runs database migrations.

Parameters:

  StackName:
    Type: String
    Description: The name of the stack

  AppUrl:
    Type: "String"
    Description: "The URL for our app (e.g. mydomain.com)"
    AllowedPattern: "[a-z0-9._-]+"

  DjangoSecretKey:
    Description: The Secret Key for backend, celery and beat containers
    Type: String
    NoEcho: true

Resources:
  MigrateTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: migrate
      ContainerDefinitions:
        - Name: migrate
          Essential: true
          Image:
            Fn::ImportValue:
              !Sub ${StackName}:BackendImage
          MemoryReservation: 128
          Command:
            - python3
            - manage.py
            - migrate
            - --no-input
          Environment:
            - Name: SECRET_KEY
              Value: !Ref DjangoSecretKey
            - Name: APP_URL
              Value: !Ref AppUrl
            - Name: DEBUG
              Value: ''
            - Name: POSTGRES_NAME
              Value: postgres
            - Name: POSTGRES_USERNAME
              Value: postgres
            - Name: POSTGRES_PASSWORD
              Value: postgres
            - Name: POSTGRES_SERVICE_HOST
              Value:
                Fn::ImportValue:
                  !Sub ${StackName}:RDSHost
            - Name: REDIS_SERVICE_HOST
              Value:
                Fn::ImportValue:
                  !Sub ${StackName}:ElastiCacheHost
            - Name: AWS_STORAGE_BUCKET_NAME
              Value: !Sub "${StackName}-assets"
            - Name: STACK_NAME
              Value: !Ref StackName
            - Name: DJANGO_SETTINGS_MODULE
              Value: 'backend.settings.production'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref MigrateCloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region

  MigrateCloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 1
