stages:
  - build
  - test
  - deploy


build:
  image: node:latest
  stage: build
  artifacts:
    untracked: true
  script:
    - npm install --progress=false
    - npm run build
    - echo "Build Complete"


deploy:
  image: python:3.6
  stage: deploy
  dependencies:
    - build
  before_script:
    - pip install awscli
    - aws iam get-user
  script:
    - aws s3 sync dist/ s3://briancaffey.com/ --delete
