stages:
  - test
  - build
  - deploy

unit:
  image: node:latest
  stage: test
  before_script:
    - npm install --progress=false
  script:
    - npm run lint
    - npm run test:unit
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

e2e:
  image: cypress/base:10
  stage: test
  before_script:
    - npm install --progress=false
  script:
    - npm run serve &
    - $(npm bin)/cypress run
  artifacts:
    paths:
      - tests/e2e/videos/
      - tests/e2e/screenshots/
    expire_in: 7 days

build:
  image: node:latest
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm install --progress=false
    - npm run build
    - echo "Build Complete"

deploy:
  image: python:3.6
  stage: deploy
  dependencies:
    - build
  before_script:
    - pip install awscli
    - aws iam get-user
  script:
    - aws s3 sync dist/ s3://briancaffey.com/ --delete
