Description: >
  This service runs the Daphne server.

Parameters:

  ImageUrl:
    Type: String
    Description: ECR Image

  StackName:
    Type: String
    Description: The name of the stack

  AppUrl:
    Type: "String"
    Description: "The URL for our app (e.g. mydomain.com)"
    AllowedPattern: "[a-z0-9._-]+"

  DesiredCount:
    Description: How many instances of this task should we run across our cluster?
    Type: Number
    Default: 2

  Listener:
    Description: The Application Load Balancer listener to register with
    Type: String

  ServiceRole:
    Description: An IAM Role that grants the service access to register/unregister with the Application Load Balancer (ALB).
    Type: String

  DjangoSecretKey:
    Description: The Secret Key for backend, celery and beat containers
    Type: String
    NoEcho: true

Resources:
  DaphneService:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      Cluster:
        Fn::ImportValue:
          !Sub ${StackName}:ECSCluster
      Role: !Ref ServiceRole
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: "daphne"
          ContainerPort: 9000
          TargetGroupArn: !Ref DaphneTargetGroup

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: daphne
      ContainerDefinitions:
        - Name: daphne
          Essential: true
          Image: !Ref ImageUrl
          MemoryReservation: 128
          Command:
            - "daphne"
            - "backend.asgi:application"
            - "--bind"
            - "0.0.0.0"
            - "--port"
            - "9000"
          Environment:
            - Name: SECRET_KEY
              Value: !Ref DjangoSecretKey
            - Name: APP_URL
              Value: !Ref AppUrl
            - Name: DEBUG
              Value: ''
            - Name: POSTGRES_NAME
              Value: postgres
            - Name: POSTGRES_USERNAME
              Value: postgres
            - Name: POSTGRES_PASSWORD
              Value: postgres
            - Name: POSTGRES_SERVICE_HOST
              Value:
                Fn::ImportValue:
                  !Sub ${StackName}:RDSHost
            - Name: REDIS_SERVICE_HOST
              Value:
                Fn::ImportValue:
                  !Sub ${StackName}:ElastiCacheHost
            - Name: AWS_STORAGE_BUCKET_NAME
              Value: !Sub "${StackName}-assets"
            - Name: STACK_NAME
              Value: !Ref StackName
            - Name: DJANGO_SETTINGS_MODULE
              Value: 'backend.settings.production'
          PortMappings:
            - ContainerPort: 9000
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref DaphneCloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region

  DaphneTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId:
        Fn::ImportValue:
          !Sub ${StackName}:VpcId
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 300
      HealthCheckPath: /api/hello-world
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref Listener
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - "/ws/*"
      Actions:
        - TargetGroupArn: !Ref DaphneTargetGroup
          Type: forward

  DaphneCloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 7
