version: "3.7"

services:
  frontend:
    image: frontend:2
    build:
      context: ../
      dockerfile: nginx/minikube/Dockerfile
      args:
        - FULL_DOMAIN_NAME=minikube.local
        - GOOGLE_OAUTH2_KEY=google123
        - GITHUB_KEY=github123

  backend:
    image: backend:1
    build:
      context: ../backend/
      dockerfile: scripts/dev/Dockerfile
