AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template deploys a single node Elasticache cluster that runs Redis

Parameters:
  VPC:
    Description: Main VPC
    Type: AWS::EC2::VPC::Id

  PrivateSubnets:
    Description: List of private subnets for RDS
    Type: String

  SourceSecurityGroupId:
    Description: VPC Security Group ID
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  ElasticacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Elasticache Security Group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379

  ElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: ElasticacheRedis Subnet Group
      Description: Elasticache Subnet Group
      SubnetIds: !Split [',', !Ref PrivateSubnets]

  ElastiCacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      Engine: redis
      ClusterName: Elasticache Redis Cluster
      NumCacheNodes: 1
      CacheSubnetGroupName: !Ref ElasticacheSubnetGroup
      VpcSecurityGroupIds:
        - !GetAtt ElasticacheSecurityGroup.GroupId

Outputs:
  ElastiCacheEndpoint:
    Description: Endpoint for Elasticache Cluster
    Value: !GetAtt ElastiCacheCluster.RedisEndpoint.Address
