Description: >
  This template deploys a static site using S3, CloudFront and Route53.

Parameters:
  StackName:
    Type: String
    Description: The name of the stack

  AppUrl:
    Type: "String"
    Description: "The URL for our app (e.g. mydomain.com)"
    AllowedPattern: "[a-z0-9._-]+"

  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: "The hosted zone ID to add the Route 53 recordset to."

  WildcardSSLCertificateArn:
    Type: "String"
    Description: "ARN pointing to an SSL cert to use for this app URL."
    AllowedPattern: "arn:aws:acm:.*"
    ConstraintDescription: "Please supply a valid ARN to a certificate."

Resources:
  StaticSiteBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref AppUrl
      AccessControl: "PublicRead"
  StaticSiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    DependsOn: StaticSiteBucket
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${StaticSiteBucket.Arn}/*"
  CFDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref AppUrl
          - !Sub "*.${AppUrl}"
        DefaultRootObject: "index.html"
        DefaultCacheBehavior:
          TargetOriginId: !Sub "S3-${StaticSiteBucket}"
          ViewerProtocolPolicy: "redirect-to-https"
          ForwardedValues:
            QueryString: false
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: "/index.html"
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/index.html"
        Enabled: true
        Origins:
          - DomainName: !GetAtt StaticSiteBucket.DomainName
            Id: !Sub "S3-${StaticSiteBucket}"
            S3OriginConfig:
              OriginAccessIdentity: ""
        ViewerCertificate:
          AcmCertificateArn: !Ref WildcardSSLCertificateArn
          SslSupportMethod: "sni-only"

  DNSRecord:
    Type: "AWS::Route53::RecordSet"
    DependsOn: CFDistribution
    Properties:
      AliasTarget:
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !GetAtt CFDistribution.DomainName
      Name: !Sub "${AppUrl}."
      Type: "A"
      HostedZoneId: !Ref HostedZoneId

  WildCardDNSRecord:
    Type: "AWS::Route53::RecordSet"
    DependsOn: CFDistribution
    Properties:
      AliasTarget:
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !GetAtt CFDistribution.DomainName
      Name: !Sub "*.${AppUrl}."
      Type: "A"
      HostedZoneId: !Ref HostedZoneId
