.Release backend:
  stage: release
  image: docker:stable
  only:
    master
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl jq python py-pip
    - pip install gcloud (google sdk)

Terraform Plan:
  stage: deploy
  image: hashicorp/terraform:light
  before_script:
    - pwd
    - ls
    - cd terraform
    - echo $GCP_SERVICE_ACCOUNT | base64 -d > ./terraform/account.json
    - terraform init -var-file=production.tfvars
  script:
    - terraform plan -out "planfile" -var-file=production.tfvars
  artifacts:
    paths:
      - planfile